### PR TITLE
fix: bgp neighbor description vrf support

### PR DESCRIPTION
**Pull request by tynany**
Fix https://github.com/tynany/frr_exporter/issues/74 by supporting BGP neighbor descriptions when using VRFs.

### CODE REVIEW

**Comment by tynany** [comment]
@dswarbrick do you have time to review the PR?

**Comment by 33Fraise33** [comment]
I am available to test if you want? how do I build this specific branch with go (I don't have any real go experience)

**Comment by 33Fraise33** [comment]
It seems to be working, I'll let it run for a few minutes to see if prometheus gives any errors.

**Comment by 33Fraise33** [comment]
I do still have the following error in my output. I do not have this error on 1.1.1
```
sudo /usr/local/bin/frr_exporter --frr.socket.dir-path=/var/run/frr --no-collector.ospf --no-collector.bfd --collector.bgp6 --collector.bgp.peer-descriptions --collector.bgp.peer-descriptions.plain-text
level=info ts=2022-07-08T08:54:59.528Z caller=frr_exporter.go:65 msg="Starting frr_exporter" version="(version=1.1.2-rc1, branch=HEAD, revision=dacd6ede146a014f0c76eca8562b2a771de4ac59)"
level=info ts=2022-07-08T08:54:59.528Z caller=frr_exporter.go:66 msg="Build context" build_context="(go=go1.17.11, user=root@db54bffe9904, date=20220708-08:27:45)"
level=info ts=2022-07-08T08:54:59.528Z caller=frr_exporter.go:67 msg="Listening on address" address=:9342
level=info ts=2022-07-08T08:54:59.529Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=error ts=2022-07-08T08:55:51.655Z caller=collector.go:126 msg="collector scrape failed" name=bgp duration_seconds=0.002214144 err="cannot process output of show bgp vrf all ipv4 unicast summary json: unexpected end of JSON input: command output: {\n\"default\":{}\n,\n\"remotesites\":{\n  \"routerId\":\"10.10.33.1\",\n  \"as\":211184,\n  \"vrfId\":12,\n  \"vrfName\":\"remotesites\",\n  \"tableVersion\":128,\n  \"ribCount\":19,\n  \"ribMemory\":3496,\n  \"peerCount\":3,\n  \"peerMemory\":2222424,\n  \"peerGroupCount\":1,\n  \"peerGroupMemory\":64,\n  \"peers\":{\n    \"10.10.34.2\":{\n      \"remoteAs\":65501,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":166213,\n      \"msgSent\":166346,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w3d10h\",\n      \"peerUptimeMsec\":903343000,\n      \"peerUptimeEstablishedEpoch\":1656367208,\n      \"pfxRcd\":4,\n      \"pfxSnt\":9,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":12,\n      \"connectionsDropped\":11,\n      \"desc\":\"ASGARDv4\",\n      \"idType\":\"ipv4\"\n    },\n    \"10.10.34.6\":{\n      \"remoteAs\":65511,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":165818,\n      \"msgSent\":165959,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w2d00h\",\n      \"peerUptimeMsec\":779206000,\n      \"peerUptimeEstablishedEpoch\":1656491345,\n      \"pfxRcd\":1,\n      \"pfxSnt\":9,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":21,\n      \"connectionsDropped\":20,\n      \"desc\":\"MOMv4\",\n      \"idType\":\"ipv4\"\n    },\n    \"10.10.34.10\":{\n      \"remoteAs\":65502,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":166282,\n      \"msgSent\":166533,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w0d14h\",\n      \"peerUptimeMsec\":658536000,\n      \"peerUptimeEstablishedEpoch\":1656612015,\n      \"pfxRcd\":0,\n      \"pfxSnt\":9,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":21,\n      \"connectionsDropped\":20,\n      \"desc\":\"SAKAARv4\",\n      \"idType\":\"ipv4\"\n    }\n  },\n  \"failedPeers\":0,\n  \"displayedPeers\":3,\n  \"totalPeers\":3,\n  \"dynamicPeers\":0,\n  \"bestPath\":{\n    \"multiPathRelax\":\"false\"\n  }\n}\n,\n\"locix\":{}\n,\n\"kleyrex\":{}\n,\n\"fogixp\":{}\n}\n"
level=error ts=2022-07-08T08:55:51.657Z caller=collector.go:126 msg="collector scrape failed" name=bgp6 duration_seconds=0.003791284 err="cannot process output of show bgp vrf all ipv6 unicast summary json: unexpected end of JSON input: command output: {\n\"default\":{\n  \"routerId\":\"193.148.249.106\",\n  \"as\":211184,\n  \"vrfId\":0,\n  \"vrfName\":\"default\",\n  \"tableVersion\":33993861,\n  \"ribCount\":288976,\n  \"ribMemory\":53171584,\n  \"peerCount\":1,\n  \"peerMemory\":740808,\n  \"peerGroupCount\":1,\n  \"peerGroupMemory\":64,\n  \"peers\":{\n    \"2a0c:9a40:1::1\":{\n      \"remoteAs\":34927,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":27165513,\n      \"msgSent\":166575,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w3d11h\",\n      \"peerUptimeMsec\":905746000,\n      \"peerUptimeEstablishedEpoch\":1656364805,\n      \"pfxRcd\":152966,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":3,\n      \"connectionsDropped\":2,\n      \"desc\":\"IFOG PEERING\",\n      \"idType\":\"ipv6\"\n    }\n  },\n  \"failedPeers\":0,\n  \"displayedPeers\":1,\n  \"totalPeers\":1,\n  \"dynamicPeers\":0,\n  \"bestPath\":{\n    \"multiPathRelax\":\"false\"\n  }\n}\n,\n\"remotesites\":{\n  \"routerId\":\"10.10.33.1\",\n  \"as\":211184,\n  \"vrfId\":12,\n  \"vrfName\":\"remotesites\",\n  \"tableVersion\":119,\n  \"ribCount\":23,\n  \"ribMemory\":4232,\n  \"peerCount\":1,\n  \"peerMemory\":740808,\n  \"peerGroupCount\":1,\n  \"peerGroupMemory\":64,\n  \"peers\":{\n    \"2a12:4946:4001:34::1:2\":{\n      \"remoteAs\":65501,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":166218,\n      \"msgSent\":166356,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w3d10h\",\n      \"peerUptimeMsec\":903343000,\n      \"peerUptimeEstablishedEpoch\":1656367208,\n      \"pfxRcd\":7,\n      \"pfxSnt\":13,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":14,\n      \"connectionsDropped\":13,\n      \"desc\":\"ASGARDv6\",\n      \"idType\":\"ipv6\"\n    }\n  },\n  \"failedPeers\":0,\n  \"displayedPeers\":1,\n  \"totalPeers\":1,\n  \"dynamicPeers\":0,\n  \"bestPath\":{\n    \"multiPathRelax\":\"false\"\n  }\n}\n,\n\"locix\":{\n  \"routerId\":\"185.1.167.89\",\n  \"as\":211184,\n  \"vrfId\":8,\n  \"vrfName\":\"locix\",\n  \"tableVersion\":2239144,\n  \"ribCount\":74125,\n  \"ribMemory\":13639000,\n  \"peerCount\":3,\n  \"peerMemory\":2222424,\n  \"peerGroupCount\":1,\n  \"peerGroupMemory\":64,\n  \"peers\":{\n    \"2001:7f8:f2:e1::be5a\":{\n      \"remoteAs\":202409,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":1706878,\n      \"msgSent\":166560,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"2d08h33m\",\n      \"peerUptimeMsec\":203617000,\n      \"peerUptimeEstablishedEpoch\":1657066934,\n      \"pfxRcd\":38631,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":5,\n      \"connectionsDropped\":4,\n      \"desc\":\"Locix RS3\",\n      \"idType\":\"ipv6\"\n    },\n    \"2001:7f8:f2:e1::babe:1\":{\n      \"remoteAs\":202409,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":1762441,\n      \"msgSent\":166612,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"2d08h36m\",\n      \"peerUptimeMsec\":203803000,\n      \"peerUptimeEstablishedEpoch\":1657066748,\n      \"pfxRcd\":38631,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":8,\n      \"connectionsDropped\":7,\n      \"desc\":\"Locix RS1\",\n      \"idType\":\"ipv6\"\n    },\n    \"2001:7f8:f2:e1::dead:1\":{\n      \"remoteAs\":202409,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":1733366,\n      \"msgSent\":166584,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"2d08h36m\",\n      \"peerUptimeMsec\":203793000,\n      \"peerUptimeEstablishedEpoch\":1657066758,\n      \"pfxRcd\":38631,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":9,\n      \"connectionsDropped\":8,\n      \"desc\":\"Locix RS2\",\n      \"idType\":\"ipv6\"\n    }\n  },\n  \"failedPeers\":0,\n  \"displayedPeers\":3,\n  \"totalPeers\":3,\n  \"dynamicPeers\":0,\n  \"bestPath\":{\n    \"multiPathRelax\":\"false\"\n  }\n}\n,\n\"kleyrex\":{\n  \"routerId\":\"193.189.83.6\",\n  \"as\":211184,\n  \"vrfId\":7,\n  \"vrfName\":\"kleyrex\",\n  \"tableVersion\":4327533,\n  \"ribCount\":73153,\n  \"ribMemory\":13460152,\n  \"peerCount\":3,\n  \"peerMemory\":2222424,\n  \"peerGroupCount\":1,\n  \"peerGroupMemory\":64,\n  \"peers\":{\n    \"2001:7f8:33::a103:1142:1\":{\n      \"remoteAs\":31142,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":1527989,\n      \"msgSent\":166537,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w3d11h\",\n      \"peerUptimeMsec\":905767000,\n      \"peerUptimeEstablishedEpoch\":1656364784,\n      \"pfxRcd\":38029,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":3,\n      \"connectionsDropped\":2,\n      \"desc\":\"Kleyrex RS1\",\n      \"idType\":\"ipv6\"\n    },\n    \"2001:7f8:33::a103:1142:2\":{\n      \"remoteAs\":31142,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":1528987,\n      \"msgSent\":166535,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w3d11h\",\n      \"peerUptimeMsec\":905762000,\n      \"peerUptimeEstablishedEpoch\":1656364789,\n      \"pfxRcd\":38025,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":3,\n      \"connectionsDropped\":2,\n      \"desc\":\"Kleyrex RS2\",\n      \"idType\":\"ipv6\"\n    },\n    \"2001:7f8:33::a103:1142:3\":{\n      \"remoteAs\":31142,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":1532042,\n      \"msgSent\":166537,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"01w3d11h\",\n      \"peerUptimeMsec\":905764000,\n      \"peerUptimeEstablishedEpoch\":1656364787,\n      \"pfxRcd\":38025,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":3,\n      \"connectionsDropped\":2,\n      \"desc\":\"Kleyrex RS3\",\n      \"idType\":\"ipv6\"\n    }\n  },\n  \"failedPeers\":0,\n  \"displayedPeers\":3,\n  \"totalPeers\":3,\n  \"dynamicPeers\":0,\n  \"bestPath\":{\n    \"multiPathRelax\":\"false\"\n  }\n}\n,\n\"fogixp\":{\n  \"routerId\":\"185.1.147.45\",\n  \"as\":211184,\n  \"vrfId\":10,\n  \"vrfName\":\"fogixp\",\n  \"tableVersion\":128916,\n  \"ribCount\":1178,\n  \"ribMemory\":216752,\n  \"peerCount\":2,\n  \"peerMemory\":1481616,\n  \"peerGroupCount\":1,\n  \"peerGroupMemory\":64,\n  \"peers\":{\n    \"2001:7f8:ca:1::77\":{\n      \"remoteAs\":210387,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":63692,\n      \"msgSent\":55799,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"2d08h19m\",\n      \"peerUptimeMsec\":202764000,\n      \"peerUptimeEstablishedEpoch\":1657067787,\n      \"pfxRcd\":1,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":6,\n      \"connectionsDropped\":5,\n      \"desc\":\"Bubacarr Sowe\",\n      \"idType\":\"ipv6\"\n    },\n    \"2001:7f8:ca:1::111\":{\n      \"remoteAs\":47498,\n      \"localAs\":211184,\n      \"version\":4,\n      \"msgRcvd\":97457,\n      \"msgSent\":55929,\n      \"tableVersion\":0,\n      \"outq\":0,\n      \"inq\":0,\n      \"peerUptime\":\"2d08h19m\",\n      \"peerUptimeMsec\":202767000,\n      \"peerUptimeEstablishedEpoch\":1657067784,\n      \"pfxRcd\":606,\n      \"pfxSnt\":1,\n      \"state\":\"Established\",\n      \"peerState\":\"OK\",\n      \"connectionsEstablished\":4,\n      \"connectionsDropped\":3,\n      \"desc\":\"FogIXP RS1\",\n      \"idType\":\"ipv6\"\n    }\n  },\n  \"failedPeers\":0,\n  \"displayedPeers\":2,\n  \"totalPeers\":2,\n  \"dynamicPeers\":0,\n  \"bestPath\":{\n    \"multiPathRelax\":\"false\"\n  }\n}\n}\n"
```

**Comment by tynany** [comment]
@33Fraise33 sorry for the delay with this. I am unable to replicate the error you are getting. Can you please send me a scrubbed copy of your FRR config?

**Comment by 33Fraise33** [comment]
> @33Fraise33 sorry for the delay with this. I am unable to replicate the error you are getting. Can you please send me a scrubbed copy of your FRR config?

No worries! here is the output: 
```
Building configuration...

Current configuration:
!
frr version 8.2.2
frr defaults traditional
hostname kingpin
service integrated-vtysh-config
!
ipv6 route ::/0 2a0c:9a40:1::1 10
!
router bgp 211184
 bgp router-id 193.148.249.106
 no bgp default ipv4-unicast
 no bgp client-to-client reflection
 bgp graceful-restart
 no bgp network import-check
 neighbor default peer-group
 neighbor default timers 20 60
 neighbor 2a0c:9a40:1::1 remote-as 34927
 neighbor 2a0c:9a40:1::1 peer-group default
 neighbor 2a0c:9a40:1::1 description IFOG PEERING
 !
 address-family ipv4 unicast
  redistribute connected
  redistribute static
  neighbor default soft-reconfiguration inbound
  neighbor default route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor default route-map rm-AS211184-exact out
  import vrf remotesites
 exit-address-family
 !
 address-family ipv6 unicast
  aggregate-address 2a12:4946:4000::/44
  redistribute connected
  redistribute static
  neighbor default activate
  neighbor default soft-reconfiguration inbound
  neighbor default route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor default route-map rm-AS211184-exact out
  import vrf locix
  import vrf kleyrex
  import vrf remotesites
 exit-address-family
exit
!
router bgp 211184 vrf remotesites
 bgp router-id 10.10.33.1
 no bgp default ipv4-unicast
 no bgp client-to-client reflection
 no bgp network import-check
 neighbor remotesites peer-group
 neighbor remotesites timers 20 60
 neighbor 10.10.34.2 remote-as 65501
 neighbor 10.10.34.2 peer-group remotesites
 neighbor 10.10.34.2 description ASGARD
 neighbor 10.10.34.6 remote-as 65511
 neighbor 10.10.34.6 peer-group remotesites
 neighbor 10.10.34.6 description MOMv4
 neighbor 10.10.34.10 remote-as 65502
 neighbor 10.10.34.10 peer-group remotesites
 neighbor 10.10.34.10 description SAKAARv4
 neighbor 10.10.34.14 remote-as 65512
 neighbor 10.10.34.14 peer-group remotesites
 neighbor 10.10.34.14 description DADv4
 neighbor 10.10.34.18 remote-as 65503
 neighbor 10.10.34.18 peer-group remotesites
 neighbor 10.10.34.18 description MIDGUARDv4
 neighbor 2a12:4946:4001:34::1:2 remote-as 65501
 neighbor 2a12:4946:4001:34::1:2 peer-group remotesites
 neighbor 2a12:4946:4001:34::1:2 description ASGARDv6
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor remotesites soft-reconfiguration inbound
  neighbor remotesites route-map rm-REMOTE_SITES-in in
  neighbor remotesites route-map rm-REMOTE_SITES-out out
  neighbor 10.10.34.2 activate
  neighbor 10.10.34.2 route-map rm-REMOTE_SITES-in in
  neighbor 10.10.34.2 route-map rm-ASGARD-out out
  neighbor 10.10.34.6 activate
  neighbor 10.10.34.10 activate
  neighbor 10.10.34.14 activate
  neighbor 10.10.34.18 activate
  neighbor 2a12:4946:4001:34::1:2 route-map rm-REMOTE_SITES-in in
  neighbor 2a12:4946:4001:34::1:2 route-map rm-ASGARD-out out
  import vrf default
 exit-address-family
 !
 address-family ipv6 unicast
  aggregate-address 2a12:4946:4000::/44
  redistribute connected
  neighbor remotesites soft-reconfiguration inbound
  neighbor remotesites route-map rm-REMOTE_SITES-in in
  neighbor remotesites route-map rm-REMOTE_SITES-out out
  neighbor 10.10.34.2 route-map rm-REMOTE_SITES-in in
  neighbor 10.10.34.2 route-map rm-ASGARD-out out
  neighbor 2a12:4946:4001:34::1:2 activate
  neighbor 2a12:4946:4001:34::1:2 route-map rm-REMOTE_SITES-in in
  neighbor 2a12:4946:4001:34::1:2 route-map rm-ASGARD-out out
  import vrf route-map rm-DEFUALT_TO_REMOTE
  import vrf default
 exit-address-family
exit
!
router bgp 211184 vrf locix
 bgp router-id 185.1.167.89
 no bgp default ipv4-unicast
 no bgp client-to-client reflection
 bgp graceful-restart
 no bgp network import-check
 neighbor locix peer-group
 neighbor locix remote-as 202409
 neighbor locix timers 20 60
 neighbor 2001:7f8:f2:e1::be5a peer-group locix
 neighbor 2001:7f8:f2:e1::be5a description Locix RS3
 neighbor 2001:7f8:f2:e1::babe:1 peer-group locix
 neighbor 2001:7f8:f2:e1::babe:1 description Locix RS1
 neighbor 2001:7f8:f2:e1::dead:1 peer-group locix
 neighbor 2001:7f8:f2:e1::dead:1 description Locix RS2
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor locix soft-reconfiguration inbound
  neighbor locix route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor locix route-map rm-AS211184-exact out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2a12:4946:4000::/44
  redistribute connected
  neighbor locix activate
  neighbor locix soft-reconfiguration inbound
  neighbor locix route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor locix route-map rm-AS211184-exact out
  import vrf route-map rm-AS211184
  import vrf default
 exit-address-family
exit
!
router bgp 211184 vrf kleyrex
 bgp router-id 193.189.83.6
 no bgp default ipv4-unicast
 no bgp client-to-client reflection
 bgp graceful-restart
 no bgp network import-check
 neighbor kleyrex peer-group
 neighbor kleyrex remote-as 31142
 neighbor kleyrex timers 20 60
 neighbor 2001:7f8:33::a103:1142:1 peer-group kleyrex
 neighbor 2001:7f8:33::a103:1142:1 description Kleyrex RS1
 neighbor 2001:7f8:33::a103:1142:2 peer-group kleyrex
 neighbor 2001:7f8:33::a103:1142:2 description Kleyrex RS2
 neighbor 2001:7f8:33::a103:1142:3 peer-group kleyrex
 neighbor 2001:7f8:33::a103:1142:3 description Kleyrex RS3
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor kleyrex soft-reconfiguration inbound
  neighbor kleyrex route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor kleyrex route-map rm-AS211184-exact out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2a12:4946:4000::/44
  redistribute connected
  neighbor kleyrex activate
  neighbor kleyrex soft-reconfiguration inbound
  neighbor kleyrex route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor kleyrex route-map rm-AS211184-exact out
  import vrf route-map rm-AS211184
  import vrf default
 exit-address-family
exit
!
router bgp 211184 vrf fogixp
 bgp router-id 185.1.147.45
 no bgp default ipv4-unicast
 no bgp client-to-client reflection
 bgp graceful-restart
 no bgp network import-check
 neighbor fogixp peer-group
 neighbor fogixp timers 20 60
 neighbor 2001:7f8:ca:1::77 remote-as 210387
 neighbor 2001:7f8:ca:1::77 peer-group fogixp
 neighbor 2001:7f8:ca:1::77 description Bubacarr Sowe
 neighbor 2001:7f8:ca:1::111 remote-as 47498
 neighbor 2001:7f8:ca:1::111 peer-group fogixp
 neighbor 2001:7f8:ca:1::111 description FogIXP RS1
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor fogixp soft-reconfiguration inbound
  neighbor fogixp route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor fogixp route-map rm-AS211184-exact out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2a12:4946:4000::/44
  redistribute connected
  neighbor fogixp activate
  neighbor fogixp soft-reconfiguration inbound
  neighbor fogixp route-map rm-DEFAULT_ONLY_PUBLIC in
  neighbor fogixp route-map rm-AS211184-exact out
  import vrf route-map rm-AS211184
  import vrf default
 exit-address-family
exit
!
ip prefix-list pl-default-public seq 5 permit 0.0.0.0/0 ge 0 le 24
ip prefix-list pl-default seq 5 permit 0.0.0.0/0
ip prefix-list pl-RFC1918 seq 5 permit 10.0.0.0/8 ge 8
ip prefix-list pl-RFC1918 seq 10 permit 172.16.0.0/12 ge 12
ip prefix-list pl-RFC1918 seq 15 permit 192.168.0.0/16 ge 16
ip prefix-list pl-LocalIpv4s seq 5 permit 10.10.33.1/32
ip prefix-list pl-LocalIpv4s seq 10 permit 193.148.249.0/24
ip prefix-list pl-LocalIpv4s seq 15 permit 185.1.166.0/23
ip prefix-list pl-MGMT seq 5 permit 172.16.33.0/24
ip prefix-list pl-MGMT seq 10 permit 10.33.0.0/24
ip prefix-list pl-MGMT seq 15 permit 10.10.33.1/32
!
ipv6 prefix-list pl-default-public seq 5 permit ::/0 ge 0 le 48
ipv6 prefix-list pl-default seq 5 permit ::/0
ipv6 prefix-list pl-AS211184-exact seq 5 permit 2a12:4946:4000::/44
ipv6 prefix-list pl-AS211184 seq 5 permit 2a12:4946:4000::/44 ge 44
!
route-map rm-DEFAULT_ONLY_PUBLIC permit 10
 match ip address prefix-list pl-default-public
exit
!
route-map rm-DEFAULT_ONLY_PUBLIC permit 20
 match ipv6 address prefix-list pl-default-public
exit
!
route-map rm-AS211184-exact permit 10
 match ipv6 address prefix-list pl-AS211184-exact
exit
!
route-map rm-AS211184 permit 10
 match ipv6 address prefix-list pl-AS211184
exit
!
route-map rm-REMOTE_SITES-in permit 10
 match ipv6 address prefix-list pl-AS211184
exit
!
route-map rm-REMOTE_SITES-in permit 20
 match ip address prefix-list pl-RFC1918
exit
!
route-map rm-REMOTE_SITES-out permit 10
 match ipv6 address prefix-list pl-AS211184
exit
!
route-map rm-REMOTE_SITES-out permit 20
 match ip address prefix-list pl-MGMT
exit
!
route-map rm-ASGARD-out permit 10
 match ipv6 address prefix-list pl-AS211184
exit
!
route-map rm-ASGARD-out permit 20
 match ip address prefix-list pl-RFC1918
exit
!
route-map rm-ASGARD-out permit 30
 match ipv6 address prefix-list pl-default
exit
!
route-map rm-LocalIpv4s permit 10
 match ip address prefix-list pl-LocalIpv4s
exit
!
route-map rm-default permit 10
 match ipv6 address prefix-list pl-default
exit
!
route-map rm-default permit 20
 match ip address prefix-list pl-default
exit
!
route-map rm-DEFUALT_TO_REMOTE permit 10
 match ipv6 address prefix-list pl-AS211184
exit
!
route-map rm-DEFUALT_TO_REMOTE permit 20
 match ipv6 address prefix-list pl-default
exit
!
end

```

**Comment by tynany** [comment]
@33Fraise33 thanks. I am still unable to replicate the issue with your configuration. Can you let me know the platform and FRR version you're using? 

It's strange the JSON shown in the error message is valid, even though the error "unexpected end of JSON" is thrown.

**Comment by 33Fraise33** [comment]
> @33Fraise33 thanks. I am still unable to replicate the issue with your configuration. Can you let me know the platform and FRR version you're using?
> 
> It's strange the JSON shown in the error message is valid, even though the error "unexpected end of JSON" is thrown.

Hmmm I am not sure where I was running the exporter. I am running the latest version now and it is working and scraping correctly but I still have no descriptions for non default vrfs. 

image
image

**Comment by tynany** [comment]
Looks like you are using 1.1.1 instead of 1.1.2-rc1:

image

**Comment by 33Fraise33** [comment]
Hello,

I noticed that as well but I actually downloaded the prelease bundle and ran that. You can see that by the folder name which was auto created by untarring the file

**Pull request merged**
